### ISSUE TITLE
Patcher server is down

### ISSUE THREAD

**Issue by Quadraxis-v2** [RiiConnect24/WiiWare-Patcher#42]
**Short Description:** the server where the patching scripts gets the actual patcher from has been returning 403 for the last few days (https://patcher.rc24.xyz)
**Notes:**
**Patcher Version:** 2.2.2
**Operating System:** Windows 11 64 bits

**Comment by AymericKing** [comment]
Same

**Comment by KcrPL** [comment]
This issue has been fixed.
